services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sqlserver-local
    restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "SqlServer@123456"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./database:/var/opt/mssql/backup

volumes:
  sqlserver-data:
